apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-api
  template:
    metadata:
      labels:
        app: travel-api
    spec:
      containers:
      - name: travel-api
        image: afrobdul-travel-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "sqlite:///./travel.db"
---
apiVersion: v1
kind: Service
metadata:
  name: travel-api-service
spec:
  selector:
    app: travel-api
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000